### ISSUE TITLE
Fix `go` versioning

### ISSUE THREAD

**Issue by trym-b** [nlnwa/veidemann-api#61]
The current `go` versioning does not work as intended, as the latest version is imported as `github.com/nlnwa/veidemann-api/go v0.0.0-20230707060218-f1a798aaa910` and not as `v1.0.0`

**Comment by maeb** [comment]
I believe it is not trivial to have the `go.mod` in a subdirectory. See https://github.com/golang/go/issues/34055.

**Comment by maeb** [comment]
I think a solution is to move the module files `go.mod` and `go.sum` to the root of the repository and rename the module path to `github.com/nlnwa/veidemann-api`.

**Comment by maeb** [comment]
Java projects use this repository via jitpack.io and it seems it requires versions without 'v' prefix: https://github.com/jitpack/jitpack.io/issues/384, so to support both go and java we would need to dual tag releases with and without the 'v' prefix.

**Comment by maeb** [comment]
This comment seems to suggest that 'v' prefix works with jitpack: https://github.com/jitpack/jitpack.io/issues/407#issue-130646735

If that is the case we should standardize on `vX.Y.Z`.
